//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTITTracNghiem.DuLieu
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BAITHI
    {
        public string MASV { get; set; }
        public string MAMH { get; set; }
        public short LAN { get; set; }
        public int CAUHOI { get; set; }
        public string SVCHON { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual BANGDIEM BANGDIEM { get; set; }
        public virtual BODE BODE { get; set; }
    }
}
