//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTITTracNghiem.DuLieu
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAOVIEN_DANGKY
    {
        public string MAGV { get; set; }
        public string MAMH { get; set; }
        public string MALOP { get; set; }
        public string TRINHDO { get; set; }
        public Nullable<System.DateTime> NGAYTHI { get; set; }
        public short LAN { get; set; }
        public Nullable<short> SOCAUTHI { get; set; }
        public Nullable<short> THOIGIAN { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual MONHOC MONHOC { get; set; }
    }
}
