//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTITTracNghiem.DuLieu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TRACNGHIEMEntities : DbContext
    {
        public TRACNGHIEMEntities()
            : base("name=TRACNGHIEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANGDIEM> BANGDIEMs { get; set; }
        public virtual DbSet<BODE> BODEs { get; set; }
        public virtual DbSet<COSO> COSOes { get; set; }
        public virtual DbSet<CT_BAITHI> CT_BAITHI { get; set; }
        public virtual DbSet<GIAOVIEN> GIAOVIENs { get; set; }
        public virtual DbSet<GIAOVIEN_DANGKY> GIAOVIEN_DANGKY { get; set; }
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<MONHOC> MONHOCs { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
    
        public virtual ObjectResult<SP_DANGNHAP_Result> SP_DANGNHAP(string tENLOGIN)
        {
            var tENLOGINParameter = tENLOGIN != null ?
                new ObjectParameter("TENLOGIN", tENLOGIN) :
                new ObjectParameter("TENLOGIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DANGNHAP_Result>("SP_DANGNHAP", tENLOGINParameter);
        }
    
        public virtual int SP_DOIMATKHAU(string lGNAME, string pASS, string nEWPASS)
        {
            var lGNAMEParameter = lGNAME != null ?
                new ObjectParameter("LGNAME", lGNAME) :
                new ObjectParameter("LGNAME", typeof(string));
    
            var pASSParameter = pASS != null ?
                new ObjectParameter("PASS", pASS) :
                new ObjectParameter("PASS", typeof(string));
    
            var nEWPASSParameter = nEWPASS != null ?
                new ObjectParameter("NEWPASS", nEWPASS) :
                new ObjectParameter("NEWPASS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DOIMATKHAU", lGNAMEParameter, pASSParameter, nEWPASSParameter);
        }
    
        public virtual ObjectResult<SP_DSLOGIN_Result> SP_DSLOGIN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DSLOGIN_Result>("SP_DSLOGIN");
        }
    
        public virtual ObjectResult<SP_DSSV_LOP_Result> SP_DSSV_LOP(string mALOP)
        {
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DSSV_LOP_Result>("SP_DSSV_LOP", mALOPParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_LAYBODEMOI(string mAMH, Nullable<int> sOCAUHOI, string tRINHDO)
        {
            var mAMHParameter = mAMH != null ?
                new ObjectParameter("MAMH", mAMH) :
                new ObjectParameter("MAMH", typeof(string));
    
            var sOCAUHOIParameter = sOCAUHOI.HasValue ?
                new ObjectParameter("SOCAUHOI", sOCAUHOI) :
                new ObjectParameter("SOCAUHOI", typeof(int));
    
            var tRINHDOParameter = tRINHDO != null ?
                new ObjectParameter("TRINHDO", tRINHDO) :
                new ObjectParameter("TRINHDO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_LAYBODEMOI", mAMHParameter, sOCAUHOIParameter, tRINHDOParameter);
        }
    
        public virtual ObjectResult<SP_LAYCAUHOI_Result> SP_LAYCAUHOI(Nullable<int> sOCAUTHI, string tRINHDO, string mAMH)
        {
            var sOCAUTHIParameter = sOCAUTHI.HasValue ?
                new ObjectParameter("SOCAUTHI", sOCAUTHI) :
                new ObjectParameter("SOCAUTHI", typeof(int));
    
            var tRINHDOParameter = tRINHDO != null ?
                new ObjectParameter("TRINHDO", tRINHDO) :
                new ObjectParameter("TRINHDO", typeof(string));
    
            var mAMHParameter = mAMH != null ?
                new ObjectParameter("MAMH", mAMH) :
                new ObjectParameter("MAMH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LAYCAUHOI_Result>("SP_LAYCAUHOI", sOCAUTHIParameter, tRINHDOParameter, mAMHParameter);
        }
    
        public virtual ObjectResult<SP_REPORTBANGDIEM_Result> SP_REPORTBANGDIEM(string tenLOP, string tenMH, Nullable<short> lanTHI)
        {
            var tenLOPParameter = tenLOP != null ?
                new ObjectParameter("tenLOP", tenLOP) :
                new ObjectParameter("tenLOP", typeof(string));
    
            var tenMHParameter = tenMH != null ?
                new ObjectParameter("tenMH", tenMH) :
                new ObjectParameter("tenMH", typeof(string));
    
            var lanTHIParameter = lanTHI.HasValue ?
                new ObjectParameter("lanTHI", lanTHI) :
                new ObjectParameter("lanTHI", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_REPORTBANGDIEM_Result>("SP_REPORTBANGDIEM", tenLOPParameter, tenMHParameter, lanTHIParameter);
        }
    
        public virtual ObjectResult<SP_STTBACKUP_Result> SP_STTBACKUP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_STTBACKUP_Result>("SP_STTBACKUP");
        }
    
        public virtual int SP_TAOTAIKHOAN(string lGNAME, string pASS, string uSERNAME, string rOLE)
        {
            var lGNAMEParameter = lGNAME != null ?
                new ObjectParameter("LGNAME", lGNAME) :
                new ObjectParameter("LGNAME", typeof(string));
    
            var pASSParameter = pASS != null ?
                new ObjectParameter("PASS", pASS) :
                new ObjectParameter("PASS", typeof(string));
    
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            var rOLEParameter = rOLE != null ?
                new ObjectParameter("ROLE", rOLE) :
                new ObjectParameter("ROLE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TAOTAIKHOAN", lGNAMEParameter, pASSParameter, uSERNAMEParameter, rOLEParameter);
        }
    
        public virtual ObjectResult<SP_TENGV_Result> SP_TENGV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TENGV_Result>("SP_TENGV");
        }
    
        public virtual ObjectResult<SP_TENSV_Result> SP_TENSV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TENSV_Result>("SP_TENSV");
        }
    
        public virtual ObjectResult<SP_TIMSINHVIEN_MALOP_Result> SP_TIMSINHVIEN_MALOP(string mALOP)
        {
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TIMSINHVIEN_MALOP_Result>("SP_TIMSINHVIEN_MALOP", mALOPParameter);
        }
    
        public virtual ObjectResult<SP_TIMSINHVIEN_MASV_Result> SP_TIMSINHVIEN_MASV(string mASV)
        {
            var mASVParameter = mASV != null ?
                new ObjectParameter("MASV", mASV) :
                new ObjectParameter("MASV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TIMSINHVIEN_MASV_Result>("SP_TIMSINHVIEN_MASV", mASVParameter);
        }
    
        public virtual int SP_TRINHDO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TRINHDO");
        }
    
        public virtual int SP_XOATAIKHOAN(string lGNAME, string uSERNAME)
        {
            var lGNAMEParameter = lGNAME != null ?
                new ObjectParameter("LGNAME", lGNAME) :
                new ObjectParameter("LGNAME", typeof(string));
    
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XOATAIKHOAN", lGNAMEParameter, uSERNAMEParameter);
        }
    
        public virtual int SP_XUATGVDANGKY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XUATGVDANGKY");
        }
    }
}
